# Generated by Django 6.0.3 on 2026-03-23 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_pbac', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='auditlogmodel',
            name='pbac_audit_subject_action',
        ),
        migrations.RemoveIndex(
            model_name='auditlogmodel',
            name='pbac_audit_effect_ts',
        ),
        migrations.RemoveIndex(
            model_name='auditlogmodel',
            name='pbac_audit_resource_ts',
        ),
        migrations.DeleteModel(
            name='AuditLogModel',
        ),
        migrations.RemoveField(
            model_name='conditionmodel',
            name='policy',
        ),
        migrations.RemoveIndex(
            model_name='policymodel',
            name='pbac_policy_active_effect',
        ),
        migrations.RemoveIndex(
            model_name='policymodel',
            name='pbac_policy_active_validity',
        ),
        migrations.DeleteModel(
            name='PolicyVersionModel',
        ),
        migrations.DeleteModel(
            name='ConditionModel',
        ),
        migrations.DeleteModel(
            name='PolicyModel',
        ),
    ]
